### ISSUE TITLE
Unencrypted wallet support

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#345]
Wallets running inside a container currently need a real shell to paste the password. This is often realized by using  an ubuntu container to start from and the password is found in scripts/logs anyway. A simple container with only the daemon and client binaries is preferred

**Comment by GlenDC** [comment]
I propose the following high-level approach:

+ When creating a wallet (using `init` or `recover`) you can give a flag to create a non-encrypted wallet (in the REST API this could be implicit by not giving a passphrase). The absence of a passphrase will drop the encryption logic for the seedFile, and would not define the `EncryptionVerification` property;
+ When loading a wallet in-memory, we can auto-unlock the file, when the wallet is not encrypted. This can be assumed in case the `EncryptionVerification` property is not defined;

We do not define any logic/feature to convert a non-encrypted wallet to an encrypted wallet. It could be supported should be needed, and it would be very simple to do given my suggested approach, but given the motivation for the feature I do not see why that would be needed, hence better not to spend our energy on this.

**Comment by GlenDC** [comment]
Started working on this, but going to pause the dev on this, and instead focus on

+ https://github.com/rivine/rivine/issues/309
+ and https://github.com/rivine/rivine/issues/307

Given that I might want to change some small things in the (Rivine) wallet code, in order to allow unencrypted wallets. While they may be small, it probably will make the merging with the current Sia wallet code a bit more difficult, hence why I'll put this issue on hold for now.
