### ISSUE TITLE
Investigate how to monitor erc20 tokens for a erc20 bridge

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/rivine#458]
Create a small example:

- Contract on erc20 testnet which has some erc20 tokens (see erc20 wiki for example contract).
- Server which monitors said contract. This server is effectively a light client.
- A small webpage which will talk to our own server and shows some info (can be made to look like an exchange?)

Code can be put in the doc folder, as it can be used later in demo's.

For the webpage it might be interesting to use the latest angular.

**Comment by GlenDC** [comment]
Not sure what this example would really tell us. There is no question that what is proposed in the rivine/home issue would work. In the end, all it is, is a web server that acts as an orcacle, to which we provide a module as well as a contract in Ethereum. It's nothing new. So I'm sure that that works.

The bigger question is if this is indeed the right approach. Building a good oracle is really hard, and perhaps not something that should be done.

I talked about this with Rob before, and the nice thing about something like an atomic swap is that it requires no oracle, yet you can proof it all with signatures. I'm bringing this up, as what we really should be trying is to R&D a way to be able to have our separate funds trapped as an ERC20 token, without requiring an oracle to do so.

**Comment by GlenDC** [comment]
On the other hand, I do understand where the oracle solution comes from. Given that we're trying to connect two blockchains, and have to work with data on one chain that is coming from the other chain, it is indeed the solution that does immediately come to mind. And given that this data is also stored on the other chain once it is pre-collected by the oracle and used in a transaction, everyone can still just validate without requiring to be an oracle themselves.

So far so good. The only problem with oracles is that if you don't do it well, you might give your very secure decentralised solution a single-point-of-failure. Either because the oracle(s) crash, have some other issues or are being attacked by a third-party. In fact if the attack is good enough, it could mean someone is tampering with the data coming out of the oracle.

There have been papers written about this, and research done. So if we're somehow convinced that the oracle is the way to go, catching up with those and knowing what the best solutions currently available are, as to have a starting point. Ideally you have a solution where you can work with a large amount of oracles, such that anyone can be an oracle (possibly against payment).

Still, things would get a lot easier and secure if we can somehow prevent the use of an oracle. But not sure that is really desirable, given that would mean that anyone that wants to exchange (or be a node that exchanges for people), would require to be a connector between the two worlds. We would have to decide if that is an issue or not.

Even so, I wouldn't spend at this point any time on the web server or web site. That is really nothing that is hard or that we need to research. If we had web developers that would in fact be super easy. The hard part will be to decide if we really want to go for oracles, and if so, do that oracle part very right. That goes waay before even thinking about a website.

**Comment by LeeSmet** [comment]
As we might want to run our own erc20 explorer somewhere, we could use https://github.com/ethnamed/eth-explorer. The added advantage here is that is supposedly api compatible with etherscan, so for the demo we can just use the etherscan servers (no need to set up our own geth node and explorer for the demo).

As an added benefit, there is already a go lib for the etherscan api (which should also be compatible with the linked explorer, maybe needs some small changes), so we don't have to do this manually

**Comment by LeeSmet** [comment]
`0xd4466DAb724DD9Dc860e08E48a78D20e75361A25` fixed currency test contract on the rinkeby testnet, https://rinkeby.etherscan.io/address/0xd4466dab724dd9dc860e08e48a78d20e75361a25

**Comment by LeeSmet** [comment]
For monitoring the chain, lets make a small prototype:

- runs in light mode inside the ethereum network
- add ability to listen for events on a contract

**Comment by LeeSmet** [comment]
As it turns out, syncing in ethereum is not the same as downloading blocks/headers/whatever, but refers to verifying the crypto trie nodes. After a while this eventually completed, and since the node I'm running is supposedly in sync (going by the logs from the library). Currently I'm looking at a 110 MB database file
