### ISSUE TITLE
Explorer has slow response times

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#469]
The mobile wallet executes the following calls:
- /explorer
- /explorer/blocks/
- /explorer/hashes/

"average response time of the explorers are 2-3s the last 24h, with sometimes even 7-8s."

**Comment by robvanmieghem** [comment]
Let's do some profiling first

**Comment by GlenDC** [comment]
> E.g the `/explorer/hashes/` call will take a long time if it looks up an address which is holding block stakes

I'm assuming that that is not the "slow responses" they are referring to, given that I doubt that any of the mobile app users that were experiencing issues because of slow responses had any block stakes at all.

So if there is a problem, it is with people, with regular wallets, and probably not even that many transactions linked to it.

**Comment by LeeSmet** [comment]
@robvanmieghem how do you suggest to do the profiling?

**Comment by LeeSmet** [comment]
zip file with a svg of the explorer cpu profile isolated to the explorer calls, and the full cpu profile .prof file

[explorer.zip](https://github.com/threefoldtech/rivine/files/2840444/explorer.zip)

there does not seem to be anything out of the ordinary

**Comment by GlenDC** [comment]
Seems fine for now.
