### ISSUE TITLE
Create a multisignature extension

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/rivine#506]
tfchain implements multisignature functionality, this is useful for other chains as well so it would be good to put it in the Rivine extensions package.

**Comment by LeeSmet** [comment]
@robvanmieghem multisignature outputs are already part of the standard rivine conditions, see https://github.com/threefoldtech/rivine/blob/master/types/unlockcondition.go

**Comment by GlenDC** [comment]
Yes, they were always standard Rivine code. Reason of your confusion might be because we override them in tfchain, but that is only because we made this condition only available since a specific block height, as the tfchain launched when Rivine didn't have multisig in place yet.

Closing this as such an extension is not required as it is already part of the standard Rivine code.

**Comment by robvanmieghem** [comment]
thanks @GlenDC

**Comment by robvanmieghem** [comment]
@GlenDC since we are way past that blocklimit now, can't we drop that code from tfchain?

**Comment by GlenDC** [comment]
Yes, we could, feel free to add it to rivine/tfchain improvements.

**Comment by robvanmieghem** [comment]
https://github.com/threefoldfoundation/tfchain/issues/332
