### ISSUE TITLE
R&D explorer HA load balancing solution that works for all rivine-based chains

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/rivine#611]
Originally proposed in the following tfchain issue <https://github.com/threefoldfoundation/tfchain/issues/39>:

> goal is that the DNS of the public explorer node actually load balances between all available and known public explorer nodes, rather than just one node

It would indeed make sense that a chain exposes only one explorer DNS, and does the load balancing for one (and even multiple regions) behind the screens. Besides the regular load balancing it should also take into account that certain nodes might be active but might have a "wrong" state (e.g. by being behind or on a fork), such explorer nodes should also not be used by the load balancer I would imagine (be it temporary).

Currently chains provide multiple explorers, forcing the light clients to write some quick and dirty balancing and consensus code themselves, but this is not really a solution, and it certainly isn't a good one even if it counts as one.

**Comment by LeeSmet** [comment]
HA implies multiple backends with a consistent view of the data that will be returned. In our case, this means multiple explorers with the same active fork, which is not guaranteed. It also means the transaction pools need to be perfectly synced, which is also not a given, especially if there is a larger amount of requests coming in. Therefore, I personally am not convinced that server side HA is the right approach here, as it removes some management ability from the clients.

That being said, if we do decide to go this route, there are multiple solutions, though none of them is perfect:

- Anycast can currently not be done due to lack of a secondary site from which to announce the network. Also, anycast setup will need to take care not to create conflicting zones, where the eventual destination would then be chosen at random from the avalable nodes, which could in turn cause the client to receive inconsistent data over multiple calls. Multiple explorers have the same IP in this setup, and a single DNS record points to this IP.
- Load balancing also allows us to set up a single IP with a single DNS record (from the clients point of view), which then acts as a terminating proxy to the actual explorers (other options such as passthrough proxy are available but this requires extra management with stuff like ssl certificates). Since the load balancer is a software solution, we have full control over how it connects a client to a backend explorer. This means we can implement the logic to select healthy explorers (i.e. available and on the highest height) in the load balancer, instead of the client (such as the desktop wallet). We might still want sticky sessions, since "healty" explorers which return the same height might not necessarily be on the same fork. The problem here is that the load balancer is now a single point of failure. If the machine dies, or more generally the software is temporarily unavailable, all explorers are unavailable, thus clients can no longer connect to the network. The solution here is to once again run multiple load balancers, which in turn leads to 2 choices on how to do this: Multiple DNS entries, and multiple load balancers running on multiple physical machines, where the load balancing happens according to the same config. In this setup, a client still needs to maintain a list of multiple explorers (actually the load balancers) in case any of them goes down. But now a client can just select one at random, as they will all use the same criteria to choose the healthy backends, thus they alsways return consistent data. Alternatively we can doe anycast to the load balancers. Since these nodes then choose the healthy backends, a conflicting routing entry is not a problem here. It also means clients can just connect to a single explorer. But this solution is currently not viable due to lack of a second site.

All in all, shot to mid term the best solution would be (IMO) to run multiple load balancers on different ip/dns,  which reduces client logic to just picking a running load balancer at random, until such time where anycasting to load balancers becomes a viable option.

**Comment by LeeSmet** [comment]
After some more discussing yesterday, we came to the following solution: 2 machines to be deployed in a hardware HA setup. On each of these nodes, we run an identical load balancer which has custom short circuit logic for the backend explorers. This allows us to let clients connect to a single IP and not require any custom logic to select the healthy peers manually.

**Comment by LeeSmet** [comment]
Doing some research on possible load balancers, reveals that there might not be a ready made solution for us:

- linkderd2: Currently only runs on top of kubernetes.
- sozu: Does not support circuit breakers, also ssl certs need to be manually provided (no automated letsencrypt)
- traefik: Supports circuit breakers but it seems only using built in operators, which measure response time.

It seems the best solution would be looking into writing a custom circuit breaker for traefik

**Comment by LeeSmet** [comment]
After some more investigation it seems that HAproxy has lua scripting support, so we can use this to implement the health checks, but HAproxy does not seem to have built-in letsencrypt support for automatic https certificates. Will continue to look into this and try an example setup

**Comment by LeeSmet** [comment]
example haproxy config file:

```
global
    maxconn     20000
    log         127.0.0.1 local0
    user        haproxy
    chroot      /usr/share/haproxy
    pidfile     /run/haproxy.pid
    stats	socket /run/haproxy_admin.sock user haproxy group haproxy mode 660 level admin
    external-check
    daemon

frontend  main
    bind :5000
    mode                 http
    log                  global
    option               httplog
    option               dontlognull
    option               http_proxy
    option forwardfor    except 127.0.0.0/8
    maxconn              8000
    timeout              client  30s

    default_backend            explorer 

backend explorer
    mode	http
    balance	roundrobin
    timeout	connect 5s
    timeout	server 30s
    timeout	queue 30s
    
    http-request set-uri https://%[req.cook(SRVSD)].threefoldtoken.com%[path]?%[query]

    option external-check
    external-check command /healthcheck
    external-check path /

    cookie SRVSD insert indirect nocache

    server	explorer1 explorer.threefoldtoken.com:443 check ssl verify none cookie explorer
    server	explorer2 explorer2.threefoldtoken.com:443 check ssl verify none cookie explorer2
    server	explorer3 explorer3.threefoldtoken.com:443 check ssl verify none cookie explorer3
    server	explorer4 explorer4.threefoldtoken.com:443 check ssl verify none cookie explorer4

listen  stats
	bind		:9000
        mode            http
        log             global

        maxconn 10

        timeout client  100s
        timeout server  100s
        timeout connect 100s
        timeout queue   100s

        stats enable
        stats hide-version
        stats refresh 30s
        stats show-node
        stats uri  /
	stats auth root:rooter
```

This uses a custom healthcheck with the correct logic to determine which explorers are healthy. Healtcheck is a go binary which is copied into the chroot directory. The problem here is that the initial client request does not yet have the cookie which specifies which explorer backend to use, therefore the first request will fail. Ideally we would have an option which allows to inject the name of the backend server into the URI somehow, but that does not seem available at this time. As a result we would need some serious hacking for this method to work. This is caused by the caddy's on the backend machine doing virtual hosting - if the URI is not configured as in their config an error is returned claiming the site is not available on this interface. A possible workaround would be to have all backend servers expose the same domain, but that will conflict with the automatic https. Another approach might be to expose a regular http service in the caddy config which shares a dns amongst all servers, and does not do automatic https redirect.

**Comment by LeeSmet** [comment]
After some more discussion, we'll first check if a setup using a caddy plugin is possible. The plugin would provide the custom healthcheck for the backends, so a caddy can then be setup on a load balancer machine. It seems the best approach right now is to create a plugin which duplicates the "proxy" plugin, and uses custom logic for the healthcheck

**Comment by LeeSmet** [comment]
Working load balancer with healthcheck can be created as a caddy plugin. Working prototype created using code in github.com/LeeSmet/rivine-caddy-plugin. A custom caddy can be build by creating the following main.go file:

```
package main

import (
	"github.com/caddyserver/caddy/caddy/caddymain"
	"github.com/caddyserver/caddy/caddyhttp/httpserver"

	// plugin
	_ "github.com/LeeSmet/rivine-caddy-plugin"
)

func main() {
	httpserver.RegisterDevDirective("reb", "proxy")
	caddymain.Run()
}
```

Registering a plugin like this is not recommended according to the official docs, however the alternative is to modify the caddy source to include the plugin name in the list of directives, which is not exposed. Like this, no such custom modifications are necessary

**Comment by LeeSmet** [comment]
the explorer originally hosted at explorer.threefoldtoken.com has been moved to explorer1.threefoldtoken.com. explorer.threefoldtoken.com has been replaced with the load balancer mentioned above, proxying to the 4 individual explorers. Let's take a look at how this works out after a few days. Note, there is currently no hardware HA setup

**Comment by GlenDC** [comment]
It is still the goal to also get the HA setup working one of these weeks, @LeeSmet, together with help of @delandtj?

**Comment by LeeSmet** [comment]
yes, HA will be looked at later, once we confirm the software is working as intended

**Comment by LeeSmet** [comment]
Verified that the solution correctly marks syncing explorers as unhealthy until they caught up

**Comment by robvanmieghem** [comment]
@LeeSmet What still needs to be done?

**Comment by LeeSmet** [comment]
Still need to investigate a failover solution in case the front caddy goes down

**Comment by LeeSmet** [comment]
Code has been moved into a directory in this repo, Also a readme has been added with a why and how to build section

**Comment by robvanmieghem** [comment]
Failover solution the front  front caddy proxy is left for another issue: https://github.com/threefoldtech/rivine/issues/620
